# Generated by Django 4.0.5 on 2022-06-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of our Article')),
                ('description', models.TextField(verbose_name='Text of our Article')),
                ('is_active', models.BooleanField(default=False, verbose_name='active/unactive')),
                ('main_img', models.ImageField(upload_to='images/blogimg', verbose_name='Final picture')),
            ],
        ),
    ]
